version: "3"
services:
  hub:
    image: selenium/hub:4.1.0
  chrome:
    image: selenium/node-chrome:4.1.0
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
  firefox:
    image: selenium/node-firefox:4.1.0
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
  search-module:
    image: roronoazorroippo/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=firefox
      - HUB_HOST=hub
      - MODULE=search-module.xml
    volumes:
      - ./output/search-result:/usr/share/udemy/test-output
  book-flight-module:
    image: roronoazorroippo/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - MODULE=book-flight-module.xml
    volumes:
      - ./output/book-result:/usr/share/udemy/test-output
