version: "3"
services:
  hub:
    image: selenium/hub:4.1.0
  chrome:
    image: selenium/node-chrome:4.1.0
    shm_size: '1gb' 
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:4.1.0
    shm_size: '1gb' 
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
   search-module:
    image: vinsdocker/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=hub
      - BROWSER=firefox
      - MODULE=search-module.xml
    volumes:
      - ./output/search-result:/usr/share/udemy/test-output      
  book-flight-module:
    image: vinsdocker/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=hub
      - BROWSER=chrome
      - MODULE=book-flight-module.xml
    volumes:
      - ./output/book-result:/usr/share/udemy/test-output   
