version: "3"
services:
  hub:
    image: selenium/hub:4.1.0
  chrome:
    image: selenium/node-chrome:4.1.0
    shm_size: '2gb'
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:4.1.0
    shm_size: '2gb'   
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  search-module:
    image: roronoazorroippo/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=hub
      - BROWSER=firefox
      - MODULE=search-module.xml
    volumes:
      - E:\MAX\IT\UDEMY\Selenium_WebDriver_with_Docker_Jenkins_AWS\test-output:/usr/share/udemy/test-output      
  book-flight-module:
    image: roronoazorroippo/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=hub
      - BROWSER=chrome
      - MODULE=book-flight-module.xml
    volumes:
      - E:\MAX\IT\UDEMY\Selenium_WebDriver_with_Docker_Jenkins_AWS\test-output2:/usr/share/udemy/test-output   
